/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface HelloStencil {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
}

declare global {


  interface HTMLHelloStencilElement extends Components.HelloStencil, HTMLStencilElement {}
  var HTMLHelloStencilElement: {
    prototype: HTMLHelloStencilElement;
    new (): HTMLHelloStencilElement;
  };
  interface HTMLElementTagNameMap {
    'hello-stencil': HTMLHelloStencilElement;
  }
}

declare namespace LocalJSX {
  interface HelloStencil extends JSXBase.HTMLAttributes<HTMLHelloStencilElement> {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface IntrinsicElements {
    'hello-stencil': HelloStencil;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


